import os
import subprocess

from langchain_core.tools import tool

from src.config.slurm_template import DEFAULT_SLURM_CONFIG, SLURM_SCRIPT_TEMPLATE


@tool
def submit_slurm_job(python_script_path: str, job_name: str = "tenpy_sim"):
    """
    Submit a Python script to the Slurm cluster scheduler.
    Args:
        python_script_path: Absolute path to the .py file generated by Programmer.
        job_name: Name for the job queue.
    """
    # 1. 准备路径
    script_dir = os.path.dirname(python_script_path)
    script_name = os.path.basename(python_script_path)
    log_path = os.path.join(script_dir, "slurm_output.log")
    sbatch_path = os.path.join(script_dir, "run.sh")

    # 2. 填充模板
    sbatch_content = SLURM_SCRIPT_TEMPLATE.format(
        job_name=job_name,
        log_path=log_path,
        cpus=DEFAULT_SLURM_CONFIG["cpus"],
        time_limit=DEFAULT_SLURM_CONFIG["time_limit"],
        partition=DEFAULT_SLURM_CONFIG["partition"],
        working_dir=script_dir,
        script_name=script_name,
    )

    # 3. 写入 .sh 文件
    with open(sbatch_path, "w", encoding="utf-8") as f:
        f.write(sbatch_content)

    # 4. 调用 sbatch 命令
    try:
        # 实际提交
        result = subprocess.run(["sbatch", sbatch_path], capture_output=True, text=True)

        if result.returncode != 0:
            return f"Submission Failed: {result.stderr}"

        # 解析 Job ID (通常输出是 "Submitted batch job 123456")
        output = result.stdout.strip()
        job_id = output.split()[-1]

        return f"Success! Job submitted. ID: {job_id}. Logs will be at {log_path}. You should wait for it to finish."

    except FileNotFoundError:
        return "Error: 'sbatch' command not found. Are you on the login node?"
    except Exception as e:
        return f"System Error: {str(e)}"


@tool
def check_job_status(job_id: str):
    """Check if a Slurm job is still running using 'squeue'."""
    try:
        result = subprocess.run(
            ["squeue", "-j", job_id], capture_output=True, text=True
        )
        # 如果 squeue 输出表头但没有内容，说明作业已结束（或排队中被取消，这里简化处理）
        if job_id not in result.stdout:
            return "Job Finished (or not found in queue)."
        else:
            return "Job is still Running or Pending..."
    except Exception:
        return "Error checking status."
